spring.datasource.url=jdbc:mariadb://127.0.0.1:3306/molclass_unittest
spring.datasource.username=molclass_unit_user
spring.datasource.password=unittestPassword
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Use JDBC Template for basic querying without full JPA
spring.jpa.show-sql=false

server.port=8082
